Develop
aDukeFan/java-filmorate pull request #21
Opened 2024-05-13 12:48 UTC by aDukeFan

2024-05-14 15:19 UTC, mitya5247 approved these changes

2024-05-14 15:36 UTC, bussybee approved these changes

2024-05-14 16:31 UTC, killerop16 approved these changes

2024-05-14 16:55 UTC, SirGay0v0 approved these changes
Happy end!

2024-05-15 02:15 UTC, afomkina requested changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Вы хорошо разобрались во взаимодействие между слоями контроллер-сервис-репозиторий. У вас получились отличные запросы к таблицам. И в целом код выглядит очень чистым, его приятно читать и будет достаточно просто поддерживать. Оставила несколько незначительных комментариев, которые можно будет поправить по желанию.
Важно будет добавить описание выполненых фич в описание пулл реквеста или в файл README

2024-05-15 02:15 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +import java.util.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/ru/using-wildcard-imports-in-java/#:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D1%85%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2%20%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B5,%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D1%81%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%B0%20%D0%B8%D0%BC%D0%B5%D0%BD.) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2024-05-15 02:15 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        for (Film film : filmsWithDirectors) {
Нужно заменить циклы на [stream api](https://www.baeldung.com/java-8-streams), для этого очень пригодится `.filter`

2024-05-15 02:15 UTC, afomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2024-05-16 20:21 UTC, aDukeFan commented on src/main/resources/schema.sql
Анастасия, спасибо большое за ревью и за статью! Большинством команды было принято решение не добавлять индексы на этом этапе, поскольку мы боимся не уложиться в жесткий дедлайн. Поэтому решили разобраться с ними вне временных рамок данного проекта каждый в своем репозитории по мере желания. 

В остальном, поправили все в соответствии с замечаниями (включая ReadMe =)).

2024-05-16 20:56 UTC, mitya5247 commented on src/main/resources/schema.sql
> _Опционально_
> Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск
> 

Большое спасибо за проверку и ценные замечания и наставления по коду!)

2024-05-17 00:18 UTC, afomkina approved these changes

2024-05-17 00:18 UTC, afomkina commented on README.md
🔥

2024-05-17 07:27 UTC, merged