add grade
aDukeFan/java-filmorate pull request #25
Opened 2024-05-27 11:34 UTC by aDukeFan

2024-06-04 09:54 UTC, mysosnovskaya requested changes

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        List<Film> top = filmRepository.findAll()
Полный перебор в памяти делать строго запрещено. Если речь идет о масштабах типа кинопоиска, то тогда все фильмы к нам даже в память не влезут) Всё только через базу данных! Поставить условие where grade != null, order по оценке, limit по нужному количеству.

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        if (top.size() < count) {
На мой взгляд, если у фильма нет оценок, то он не может входить в топ. Я бы в этом случае возвращала фильмов меньше, чем запрошено. То есть если хотят 10 лучших, а у меня с оценками только 5 фильмов, то и вернуть всего 5.

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +                            return film.getGenres().stream()
Это условие тоже должно уйти в базу данных

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +                        .filter(film -> film.getGrade() != null)
Через базу данных

2024-06-04 09:54 UTC, mysosnovskaya commented on README.md
> +## Изменения от 1 июня 2024
Круто! Очень классная практика, и сразу понятно, что в ПРе сделано)

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getRecommendations(id, "likes");
Можно в query param вынести, по какому критерию выдавать рекомендации (likes или grades), чтобы не дублировать код и чтобы не было путаницы между эндпоинтами (сейчас из урла неочевидна разница между /recommendations и /best-recommendations

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +        existChecker.throwNotFountException(filmId, "films");
Эти проверки создают лишнюю нагрузку на базу данных, а большого смысла в них нет, т.к. insert запрос вернет ошибку, если ты пытаешься вставить несуществующие user_id или film_id (из-за указанных references).

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +        if (isGradeSet(userId, filmId)) {
Эта проверка тоже выглядит странной. Можно повесить unique на пару userId-filmId, тогда при вставке база данных сама проверит, что пользователь ещё не ставил оценку.  Уже минус три запроса к базе будет!)

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +        log.info("add user's '{}' grade {} to film with '{}'",
Логи обычно на уровне сервисов пишутся. Не критично, но чаще так)

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    public Film addGrade(Integer filmId, Integer userId, int value) {
Я рекомендую вынести методы с оценками в отдельный репозиторий. Обычно один репозиторий работает с одной таблицей. И ещё не понимаю, почему метод addGrade возвращает Film. Логичнее возвращать grade :)

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    public Film addGrade(Integer filmId, Integer userId, int value) {
Эти замечания (про вынести и изменить возвращаемое значение) касаются и сервисов, и репозиториев, и остальных двух методов

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    public Film removeGrade(Integer filmId, Integer userId) {
Замечания аналогичны предыдущему методу

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    public Film updateGrade(Integer filmId, Integer userId, int value) {
Замечания аналогичны предыдущему методу

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/mapper/FilmRowMapper.java
> +            if (totalGrade < 5) {
Магическое число 5 :) Лучше вынести в константы.

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        if (value > 10 || value < 1) {
Интересно, а почему вообще фронт должен вычислять, положительная это оценка или нет? Это работа бэкенда. Поэтому я бы не ругалась, а молча проставила бы нужное значение. И ещё 1 и 10 здесь - магические числа. Нужно вынести их в константы класса с понятным названием.

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +                    advisersIds.forEach(adviserId -> recommendationsSet.
n+1 запрос, нужно исправить

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +                    advisersIds.forEach(adviserId -> recommendationsSet
n+1 запрос, нужно исправить

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +    public static final int POSITIVE_GRADE_VALUE = 5;
А вот тут константы вместо магических чисел - это хорошо!) Предложу переименовать так: DEFAULT_COUNT_OF_ADIVSERS и POSITIVE_GRADE_STARTS_FROM_VALUE

2024-06-04 09:54 UTC, mysosnovskaya commented on src/main/resources/schema.sql
> +  film_id integer not null references films(id) on delete cascade,
Уже писала в коде, продублирую здесь: не хватает уникальности для связки film_id - user_id. Можно выделить их как составной первичный ключ, это автоматически и unique будет

2024-06-16 10:37 UTC, aDukeFan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        if (top.size() < count) {
done

2024-06-16 11:07 UTC, aDukeFan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        if (value > 10 || value < 1) {
"поэтому я бы не ругалась" ))))))))))))))))))))))

2024-07-15 20:05 UTC, closed without merging